//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorReportes.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=ArrDB2;uid=SYSDBA;password=masterkey")]
        public string SaariODBC_ConnectionString {
            get {
                return ((string)(this["SaariODBC_ConnectionString"]));
            }
            set {
                this["SaariODBC_ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SaariDB\\Imagenes\\SaariRed.jpg")]
        public string RutaImagen_FichaInformativa {
            get {
                return ((string)(this["RutaImagen_FichaInformativa"]));
            }
            set {
                this["RutaImagen_FichaInformativa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SaariDB\\")]
        public string RutaRepositorio {
            get {
                return ((string)(this["RutaRepositorio"]));
            }
            set {
                this["RutaRepositorio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SaariDB\\SaariCFD\\")]
        public string RutaAntilavado {
            get {
                return ((string)(this["RutaAntilavado"]));
            }
            set {
                this["RutaAntilavado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DEV10\\MSSQL17SERVER;Initial Catalog=BD_Estanza;Persist Security Info=" +
            "True;User ID=sa;Password=Rt123456/")]
        public string SaariCFD_ConnectionString {
            get {
                return ((string)(this["SaariCFD_ConnectionString"]));
            }
            set {
                this["SaariCFD_ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DI")]
        public string AxaptaTipoPoliza {
            get {
                return ((string)(this["AxaptaTipoPoliza"]));
            }
            set {
                this["AxaptaTipoPoliza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contabilidad")]
        public string AxaptaTipoCuenta {
            get {
                return ((string)(this["AxaptaTipoCuenta"]));
            }
            set {
                this["AxaptaTipoCuenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OPOPVEIN1")]
        public string AxaptaCentroCosto {
            get {
                return ((string)(this["AxaptaCentroCosto"]));
            }
            set {
                this["AxaptaCentroCosto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRANOF")]
        public string AxaptaFinanciera {
            get {
                return ((string)(this["AxaptaFinanciera"]));
            }
            set {
                this["AxaptaFinanciera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INM")]
        public string AxaptaProposito {
            get {
                return ((string)(this["AxaptaProposito"]));
            }
            set {
                this["AxaptaProposito"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IVA16")]
        public string AxaptaGISobreVentas {
            get {
                return ((string)(this["AxaptaGISobreVentas"]));
            }
            set {
                this["AxaptaGISobreVentas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GEN")]
        public string AxaptaGIPorVentaArticulos {
            get {
                return ((string)(this["AxaptaGIPorVentaArticulos"]));
            }
            set {
                this["AxaptaGIPorVentaArticulos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000001")]
        public string AxaptaUsuario {
            get {
                return ((string)(this["AxaptaUsuario"]));
            }
            set {
                this["AxaptaUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContpaqMask {
            get {
                return ((string)(this["ContpaqMask"]));
            }
            set {
                this["ContpaqMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PolizaPorRango {
            get {
                return ((bool)(this["PolizaPorRango"]));
            }
            set {
                this["PolizaPorRango"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XAXX010101000")]
        public string rfcGenericoNacional {
            get {
                return ((string)(this["rfcGenericoNacional"]));
            }
            set {
                this["rfcGenericoNacional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XEXX010101000")]
        public string rfcGenericoExtranjero {
            get {
                return ((string)(this["rfcGenericoExtranjero"]));
            }
            set {
                this["rfcGenericoExtranjero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PermisosInmobiliaria {
            get {
                return ((bool)(this["PermisosInmobiliaria"]));
            }
            set {
                this["PermisosInmobiliaria"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool usarSinComplementos {
            get {
                return ((bool)(this["usarSinComplementos"]));
            }
            set {
                this["usarSinComplementos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CRPs {
            get {
                return ((bool)(this["CRPs"]));
            }
            set {
                this["CRPs"] = value;
            }
        }
    }
}
